### ISSUE TITLE
Compilation error: "Package 'lilv-0', required by 'virtual:world', not found"

### ISSUE THREAD

**Issue by rchastain** [brummer10/CairoColorPicker#1]
Hello! I try to compile the application (on Linux Mageia) and I get these errors:

```
Package 'lilv-0', required by 'virtual:world', not found
```

```
../libxputty/libxputty/include/xputty.h:35:10: fatal error: cairo.h: No such file or directory
```

Would you know how to solve the error? Full output attached.

Regards.

Roland

[make.log](https://github.com/brummer10/CairoColorPicker/files/9349256/make.log)

**Comment by rchastain** [comment]
By the way, I could compile and run without problem the examples of [libxputty](https://github.com/brummer10/libxputty).

**Comment by brummer10** [comment]
Oh, my bad. lilv-0 isn't needed in any way here. I've removed it from the link list now. 
Please don't try to install it, the installer target is broken. I need to fix that as well. 
Just run it from the build folder for now. (when it build now)
let me know, please.

**Comment by rchastain** [comment]
Thank you for the quick answer.

I get another error:

```
make[1]: Entering directory '/home/roland/Documents/pascal/linux/xlib/cairo/colorpick/ColorPicker'
cc -O3 -D_FORTIFY_SOURCE=2 -Wall -Wextra -fstack-protector -fno-ident -fno-asynchronous-unwind-tables -s -DNDEBUG -DSHARE_DIR=\"/usr/share\" ./CairoColorPicker.c ./main.c -L. ../libxputty/libxputty/libxputty.a -o cairocolorpicker -fPIC -Wl,-z,noexecstack -Wl,--no-undefined -I./ -I../libxputty/libxputty/include/ `pkg-config --cflags --libs cairo x11` -lm
./CairoColorPicker.c: In function 'dummy_error_handler':
./CairoColorPicker.c:230:32: error: parameter name omitted
  230 | static int dummy_error_handler(Display *, XErrorEvent *) {
      |                                ^~~~~~~~~
./CairoColorPicker.c:230:43: error: parameter name omitted
  230 | static int dummy_error_handler(Display *, XErrorEvent *) {
      |                                           ^~~~~~~~~~~~~
make[1]: *** [Makefile:148: CairoColorPicker] Error 1
```

**Comment by brummer10** [comment]
Ah, okay, have fixed that now. (Those parameter been unused in that context)
Also the install target is fixed now, so it should install/uninstall clean
Hope anything is in shape now.

**Comment by rchastain** [comment]
Compilation, installation and execution tested successfully. Thanks.
